/**
 * Coze Health/Flux Notes Autocomplete API example
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CozeHealthfluxNotesAutocompleteApiExample) {
      root.CozeHealthfluxNotesAutocompleteApiExample = {};
    }
    root.CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors = factory(root.CozeHealthfluxNotesAutocompleteApiExample.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DefaultResponseErrors model module.
   * @module model/DefaultResponseErrors
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>DefaultResponseErrors</code>.
   * @alias module:model/DefaultResponseErrors
   * @class
   * @param message {String} 
   */
  var exports = function(message) {
    var _this = this;

    _this['message'] = message;

  };

  /**
   * Constructs a <code>DefaultResponseErrors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DefaultResponseErrors} obj Optional instance to populate.
   * @return {module:model/DefaultResponseErrors} The populated <code>DefaultResponseErrors</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * @member {String} path
   */
  exports.prototype['path'] = undefined;



  return exports;
}));


