/**
 * Coze Health/Flux Notes Autocomplete API example
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/DefaultResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DefaultResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.CozeHealthfluxNotesAutocompleteApiExample) {
      root.CozeHealthfluxNotesAutocompleteApiExample = {};
    }
    root.CozeHealthfluxNotesAutocompleteApiExample.DefaultApi = factory(root.CozeHealthfluxNotesAutocompleteApiExample.ApiClient, root.CozeHealthfluxNotesAutocompleteApiExample.DefaultResponse, root.CozeHealthfluxNotesAutocompleteApiExample.ERRORUNKNOWN);
  }
}(this, function(ApiClient, DefaultResponse, ERRORUNKNOWN) {
  'use strict';

  /**
   * Default service.
   * @module api/DefaultApi
   * @version 0.1.0
   */

  /**
   * Constructs a new DefaultApi. 
   * @alias module:api/DefaultApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the valueset operation.
     * @callback module:api/DefaultApi~valuesetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Example API returning valueset
     * @param {String} valueset value set name
     * @param {String} valuesetFragment fragment of valueset string
     * @param {module:api/DefaultApi~valuesetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.valueset = function(valueset, valuesetFragment, callback) {
      var postBody = null;

      // verify the required parameter 'valueset' is set
      if (valueset === undefined || valueset === null) {
        throw new Error("Missing the required parameter 'valueset' when calling valueset");
      }

      // verify the required parameter 'valuesetFragment' is set
      if (valuesetFragment === undefined || valuesetFragment === null) {
        throw new Error("Missing the required parameter 'valuesetFragment' when calling valueset");
      }


      var pathParams = {
      };
      var queryParams = {
        'valueset': valueset,
        'valueset_fragment': valuesetFragment,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/valueset', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the valueset_0 operation.
     * @callback module:api/DefaultApi~valueset_0Callback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Example API returning valueset
     * @param {String} valueset value set name
     * @param {String} valuesetFragment fragment of valueset string
     * @param {module:api/DefaultApi~valueset_0Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.valueset_0 = function(valueset, valuesetFragment, callback) {
      var postBody = null;

      // verify the required parameter 'valueset' is set
      if (valueset === undefined || valueset === null) {
        throw new Error("Missing the required parameter 'valueset' when calling valueset_0");
      }

      // verify the required parameter 'valuesetFragment' is set
      if (valuesetFragment === undefined || valuesetFragment === null) {
        throw new Error("Missing the required parameter 'valuesetFragment' when calling valueset_0");
      }


      var pathParams = {
      };
      var queryParams = {
        'valueset': valueset,
        'valueset_fragment': valuesetFragment,
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = [];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/valueset', 'OPTIONS',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
