/**
 * Coze Health/Flux Notes Autocomplete API example
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CozeHealthfluxNotesAutocompleteApiExample);
  }
}(this, function(expect, CozeHealthfluxNotesAutocompleteApiExample) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultResponseErrors', function() {
    it('should create an instance of DefaultResponseErrors', function() {
      // uncomment below and update the code to test DefaultResponseErrors
      //var instance = new CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors();
      //expect(instance).to.be.a(CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors);
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new CozeHealthfluxNotesAutocompleteApiExample.DefaultResponseErrors();
      //expect(instance).to.be();
    });

  });

}));
