/**
 * Coze Health/Flux Notes Autocomplete API example
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CozeHealthfluxNotesAutocompleteApiExample);
  }
}(this, function(expect, CozeHealthfluxNotesAutocompleteApiExample) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CozeHealthfluxNotesAutocompleteApiExample.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('diagnosis', function() {
      it('should call diagnosis successfully', function(done) {
        //uncomment below and update the code to test diagnosis
        //instance.diagnosis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('laboratoryOrder', function() {
      it('should call laboratoryOrder successfully', function(done) {
        //uncomment below and update the code to test laboratoryOrder
        //instance.laboratoryOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('medicalProcedure', function() {
      it('should call medicalProcedure successfully', function(done) {
        //uncomment below and update the code to test medicalProcedure
        //instance.medicalProcedure(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('medication', function() {
      it('should call medication successfully', function(done) {
        //uncomment below and update the code to test medication
        //instance.medication(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
